# Matilda Voice Development Makefile

.PHONY: help test test-cov test-fast lint format format-check type-check quality clean install dev unit integration config-tests audio-tests

PY ?= python3

help: ## Show this help message
	@echo "Matilda Voice Development Commands:"
	@echo "===================================="
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

test: ## Run all tests
	@./scripts/test.py all --force

test-cov: ## Run tests with coverage report
	@./scripts/test.py all --coverage --force

test-fast: ## Run tests quickly (no coverage)
	@./scripts/test.py unit --force

lint: ## Run linting with ruff
	@echo "Running linter..."
	@$(PY) -c "import ruff" 2>/dev/null || (echo "ruff is not installed. Install dev deps: python3 -m pip install -e '.[dev]'"; exit 1)
	@# cli.py is generated by Goobits; lint the source-of-truth instead (goobits.yaml/app_hooks.py).
	@$(PY) -m ruff check src/matilda_voice/ tests/ --extend-exclude src/matilda_voice/cli.py

format: ## Format code with black
	@echo "Formatting code..."
	@$(PY) -c "import black" 2>/dev/null || (echo "black is not installed. Install dev deps: python3 -m pip install -e '.[dev]'"; exit 1)
	@# cli.py is generated by Goobits; format the source-of-truth instead (goobits.yaml/app_hooks.py).
	@$(PY) -m black src/matilda_voice/ tests/ --line-length 120 --force-exclude 'cli\.py$$'

format-check: ## Check formatting (non-mutating)
	@echo "Checking format..."
	@$(PY) -c "import black" 2>/dev/null || (echo "black is not installed. Install dev deps: python3 -m pip install -e '.[dev]'"; exit 1)
	@# cli.py is generated by Goobits; check source-of-truth formatting instead.
	@$(PY) -m black src/matilda_voice/ tests/ --line-length 120 --check --force-exclude 'cli\.py$$'

type-check: ## Run type checking with mypy
	@echo "Running type checker..."
	@$(PY) -c "import mypy" 2>/dev/null || (echo "mypy is not installed. Install dev deps: python3 -m pip install -e '.[dev]'"; exit 1)
	@# cli.py is generated by Goobits; type-check the source-of-truth instead (goobits.yaml/app_hooks.py).
	@$(PY) -m mypy src/matilda_voice/ --exclude 'cli\.py$$'

quality: format-check lint type-check ## Run all code quality checks
	@echo "All quality checks completed!"

clean: ## Clean up build artifacts and cache
	@echo "Cleaning up..."
	@rm -rf __pycache__ .pytest_cache .mypy_cache .coverage htmlcov
	@rm -rf .artifacts/htmlcov
	@find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	@find . -type f -name "*.pyc" -delete

install: ## Install package with pipx
	@./scripts/setup.sh install

dev: ## Install in development mode
	@./scripts/setup.sh install --dev

unit: ## Run unit tests only
	@$(PY) -m pytest tests/ -m "unit or not integration" -v

integration: ## Run integration tests only
	@$(PY) -m pytest tests/ -m "integration" -v

config-tests: ## Run configuration tests only
	@$(PY) -m pytest tests/test_config.py -v

audio-tests: ## Run audio utility tests only
	@$(PY) -m pytest tests/test_audio_utils.py -v
